function M_sym = M_1dof(q1)
%M_1dof
%    M_sym = M_1dof(Q1)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    25-Nov-2025 14:18:52

M_sym = cos(q1).^2./2.0e+5+sin(q1).^2./2.0e+5+2.083333333333333e-6;
end
