function Minv_sym = Minv_twolinkrobot(in1,m1,m2,Iz1,Iz2,a1,ell1,ell2)
%Minv_twolinkrobot
%    Minv_sym = Minv_twolinkrobot(IN1,M1,M2,Iz1,Iz2,A1,ELL1,ELL2)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    13-Nov-2025 17:30:26

q2 = in1(2,:);
t2 = cos(q2);
t3 = Iz2.^2;
t4 = a1.^2;
t5 = ell1.^2;
t6 = ell2.^2;
t7 = m2.^2;
t8 = Iz1.*Iz2;
t9 = t2.^2;
t10 = m2.*t6;
t11 = -t3;
t12 = a1.*ell2.*m2.*t2;
t13 = Iz2.*m2.*t4;
t14 = Iz2.*m1.*t5;
t19 = t4.*t6.*t7;
t15 = Iz1.*t10;
t16 = Iz2.*t10;
t18 = m1.*t5.*t10;
t20 = Iz2+t10+t12;
t21 = t9.*t19;
t17 = -t16;
t22 = -t21;
t23 = t8+t11+t13+t14+t15+t17+t18+t19+t22;
t24 = 1.0./t23;
t25 = t20.*t24;
t26 = -t25;
Minv_sym = reshape([t24.*(Iz2+t10),t26,t26,t24.*(Iz1+t10+t12.*2.0+m1.*t5+m2.*t4)],[2,2]);
end
