function Ug = Ug_4dof(in1)
%Ug_4dof
%    Ug = Ug_4dof(IN1)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    09-Dec-2025 16:58:54

q1 = in1(1,:);
q2 = in1(2,:);
q3 = in1(3,:);
q4 = in1(4,:);
t2 = cos(q1);
t3 = cos(q2);
t4 = cos(q3);
t5 = cos(q4);
t6 = sin(q2);
t7 = sin(q3);
t8 = sin(q4);
t9 = t2.*t3.*t4;
t10 = t2.*t3.*t7;
t11 = t2.*t4.*t6;
t12 = t2.*t6.*t7;
t13 = -t12;
t14 = t10+t11;
t15 = t9+t13;
Ug = t2.*9.81e-2+t10.*6.62175e-1+t11.*6.62175e-1+t2.*t6.*1.103625+t5.*t14.*1.61865e-1+t5.*t15.*9.81e-2-t8.*t14.*9.81e-2+t8.*t15.*1.61865e-1+2.943e-1;
end
