function out1 = dUgdq_3dof(in1)
%dUgdq_3dof
%    OUT1 = dUgdq_3dof(IN1)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    27-Nov-2025 00:05:31

q1 = in1(1,:);
q2 = in1(2,:);
q3 = in1(3,:);
t2 = cos(q1);
t3 = cos(q2);
t4 = cos(q3);
t5 = sin(q1);
t6 = sin(q2);
t7 = sin(q3);
t8 = t3.*t4.*(3.0./4.0e+1);
t9 = t6.*t7.*(3.0./4.0e+1);
t10 = -t9;
out1 = [t5.*(-2.943e-2)-t5.*t6.*2.20725e-1-t3.*t5.*t7.*7.3575e-2-t4.*t5.*t6.*7.3575e-2;t2.*t3.*2.20725e-1+t2.*(t3.*(3.0./2.0e+1)+t8+t10).*2.943;t2.*(t8+t10).*2.943];
end
